#! /bin/sh

IMGFILE=${1-res/initfs}
MNTDIR=./initrd

# must fit to 1.44M floppy
IMG_KB_SIZE=768

dd if=/dev/zero of=$IMGFILE bs=1k count=$IMG_KB_SIZE
mke2fs -F -L initfs $IMGFILE

[ -d $MNTDIR ] || mkdir $MNTDIR

sudo mount -o loop -t ext2 $IMGFILE $MNTDIR
cd $MNTDIR

sudo mkdir boot
sudo cp ../build/kernel* boot/

sudo mkdir dev
sudo mknod dev/mem  c 1 1
sudo mknod dev/null c 1 3
sudo mknod dev/port c 1 4
sudo mknod dev/zero c 1 5
sudo mknod dev/full c 1 7
sudo mknod dev/rand c 1 8

sudo mknod dev/initrd b 1 250

sudo mknod dev/tty  c 5 0

cd -

sudo umount $MNTDIR
sudo rmdir $MNTDIR
